include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - bricks/**

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    depend_on_referenced_packages: false
